### ISSUE TITLE
Do not give up.

### ISSUE THREAD

**Issue by shdudwns** [TesseractMC/Tesseract#1]
Do not give up.
And don't you have any convertibles?
Do you have any version 1.0.5?
I'd like to get rid of the error framing error.

**Comment by NFGamerMC** [comment]
Don't Worry, this repo is not dying!

**Comment by NFGamerMC** [comment]
Yes, we do. Please Wait!

**Comment by MCPEGamerJPatGitHub** [comment]
Moved to @TesseractNetwork. https://github.com/TesseractNetwork/Tesseract

**Comment by NFGamerMC** [comment]
I am going to close this issue as it have been solved
