### ISSUE TITLE
MCPEGamerJPatGitHub

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractMC/Tesseract#13]
Please write a message on your repo that this is the new tesseract, I am going to give you admin privileges!

**Comment by MCPEGamerJPatGitHub** [comment]
which repo

**Comment by NFGamerMC** [comment]
TesseractNetwork/Tesseact

**Comment by NFGamerMC** [comment]
Also you are now admin, remember we are a team!

**Comment by MCPEGamerJPatGitHub** [comment]
I don't have write access there. But I did all I can

**Comment by NFGamerMC** [comment]
Login then Out
