### ISSUE TITLE
Item Frame issue

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractMC/Tesseract#15]
### Issue description

The item duplicated

### Steps to reproduce the issue

1. Place item in item frame
2. Remove it

### OS and versions

* Tesseract: 1.0.2
* PHP: 7.0.0
* Server OS: Ubnutu 16 x64
* Game version: PE/Win10 
* Server Host: DigitalOcean

### Crashdump, backtrace or other files

* none

**Comment by jdongel2004** [comment]
We need to say Mojang this client problem.. LoL

**Comment by NFGamerMC** [comment]
Yup, just saying!
