### ISSUE TITLE
Linux Installer

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractMC/Tesseract#23]
Just a reminder to myself.

**Comment by xZeroMCPE** [comment]
Add me as owner....

**Comment by NFGamerMC** [comment]
Only if you don't delete this and switch to @TesseractNetwork

**Comment by NFGamerMC** [comment]
Okay, complete. Please keep this repo alive

**Comment by xZeroMCPE** [comment]
@NFGamerMC where tf are the branches we had..... Anyhow.. trying to get github to restore the other repo..... lost alot of branches!

**Comment by NFGamerMC** [comment]
My version from yesterday morning had only the master branch, the other ones are not in my hands only @appledevelops. You can upload them if you have them. Me and other team have been making new ones for 1.1, testing and API 4.0.0

**Comment by xZeroMCPE** [comment]
@NFGamerMC Alright

**Comment by NFGamerMC** [comment]
Do you have any plans for this new repo, I am going to start a website for it (tesseractmc.ml) and most likely add some missing items such as beacons. You can see it at the projects tab!

**Comment by NFGamerMC** [comment]
Also can you help me setup Jenkins? http://tesseractmc.herokuapp.com

Will be adding a custom domain for it soon!

**Comment by AppleDevelops** [comment]
🤔

**Comment by NFGamerMC** [comment]
What is that supposed to mean? I have setup CircleCI but for some reason my temp. Jenkins is not working. I know how to fix it but my computer is 32bit so it can't run the Heroku CLI

**Comment by xZeroMCPE** [comment]
@NFGamerMC Original repo reverted!!
