### ISSUE TITLE
Tesseract

### ISSUE THREAD

**Issue by McGrimmi** [TesseractMC/Tesseract#3]
Work together with @TesseractNetwork, if you work together it will be better :)

**Comment by NFGamerMC** [comment]
Sorry but you willl have to ask them, we have all the builds and a more recent version!

**Comment by caspervanneck** [comment]
@NFGamerMC  great idea (:

**Comment by NFGamerMC** [comment]
Yes, I invited all members from TesseractNetwork to here. Currently I have access to Jenkins and the Lates triggered phar
