### ISSUE TITLE
Why don't you join the developer here?

### ISSUE THREAD

**Issue by shdudwns** [TesseractMC/Tesseract#5]
This is APL 4.0.0. Why don't we develop this together with a ibun developer?
https://github.com/TesseractNetwork/Tesseract

**Comment by NFGamerMC** [comment]
We are working this out now, please let us sort it out! You can become a dev here if you want?

**Comment by NFGamerMC** [comment]
That is not API 4.0.0, api 4.0.0 has resource pack support. Also the server.php says otherwise
