### ISSUE TITLE
invite in the group instead of building map

### ISSUE THREAD

**Issue by caspervanneck** [TesseractMC/Tesseract#6]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by NFGamerMC** [comment]
Please Explain a little bit more!?

**Comment by caspervanneck** [comment]
why not invite in tesseractmc

**Comment by caspervanneck** [comment]
@NFGamerMC

**Comment by MCPEGamerJPatGitHub** [comment]
useless

**Comment by NFGamerMC** [comment]
But, I am the group owner. I am tesseractmc

**Comment by caspervanneck** [comment]
@NFGamerMC@you dont understead

**Comment by caspervanneck** [comment]
i mean why you dont invite poeple in the group or team wat call it

**Comment by NFGamerMC** [comment]
Well, just tell me what you want.

**Comment by caspervanneck** [comment]
why dont invite poeple as a member ?

**Comment by caspervanneck** [comment]
my eng is bad

**Comment by NFGamerMC** [comment]
Sorry, I will make you an admin! I am monitoring this repo as I have been seeing spam!

**Comment by NFGamerMC** [comment]
Okay, done

**Comment by caspervanneck** [comment]
thnx

**Comment by NFGamerMC** [comment]
Do you know PHP? If not please don't edit code unless it is a pull request!

**Comment by caspervanneck** [comment]
yes i know php but am not a master

**Comment by NFGamerMC** [comment]
Great, me too!

**Comment by caspervanneck** [comment]
@NFGamerMC  so i get member ?

**Comment by NFGamerMC** [comment]
Yes!
